name: Provisioning Resources CI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Decode GCP Credentials
        run: |
          echo "$GCP_CREDENTIALS" | base64 -d > gcp-credentials.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=${GITHUB_WORKSPACE}/gcp-credentials.json" >> $GITHUB_ENV
        env:
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}

      - name: Initialize Terraform
        run: |
          echo "Initializing Terraform with GOOGLE_APPLICATION_CREDENTIALS set to: $GOOGLE_APPLICATION_CREDENTIALS"
          terraform init

      - name: Apply Terraform
        run: |
          terraform apply -auto-approve -var "project=${{ secrets.GCP_PROJECT_ID }}" -var "region=${{ secrets.GCP_REGION }}" -var "repository_id=${{ secrets.ARTIFACT_REPO_NAME }}" -var "zone=${{ secrets.GCP_ZONE }}"
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/gcp-credentials.json

      - name: Install jq
        run: sudo apt-get install jq

      - name: Extract Artifact Registry Service Account Key
        run: |
          JSON_KEY=$(terraform output -json artifact_registry_service_account_key | jq -r '.value.key')
          echo "ARTIFACT_REGISTRY_SERVICE_ACCOUNT_KEY=$JSON_KEY" >> $GITHUB_ENV
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/gcp-credentials.json

      - name: Capture VM External IP to File
        run: |
          terraform output -raw vm_external_ip > vm_ip.txt
