name: Provisioning Resources CI

on:
  push:
    branches:
      - main

jobs:
  provision_resources:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Decode GCP Credentials
        run: |
          echo "$GCP_CREDENTIALS" | base64 -d > gcp-credentials.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=${GITHUB_WORKSPACE}/gcp-credentials.json" >> $GITHUB_ENV
        env:
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}

      - name: Initialize Terraform
        run: terraform init
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/gcp-credentials.json

      - name: Apply Terraform
        run: terraform apply -auto-approve -var "project=${{ secrets.GCP_PROJECT_ID }}" -var "region=${{ secrets.GCP_REGION }}" -var "repository_id=${{ secrets.ARTIFACT_REPO_NAME }}" -var "zone=${{ secrets.GCP_ZONE }}"
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/gcp-credentials.json

      - name: Output VM External IP
        id: vm_ip
        run: echo "::set-output name=vm_ip::$(terraform output -raw vm_external_ip)"

      - name: Capture VM External IP to File
        run: |
          terraform output -raw vm_external_ip > vm_external_ip.txt
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/gcp-credentials.json

      - name: Upload VM External IP as an Artifact
        uses: actions/upload-artifact@v2
        with:
          name: vm-external-ip
          path: vm_external_ip.txt

      - name: Extract and Save Artifact Registry Service Account Key
        run: |
          terraform output -json artifact_registry_service_account_key | jq -r '.key' > artifact_key.txt
        shell: /usr/bin/bash -e {0}

      - name: Upload Artifact Registry Service Account Key as an Artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifact-registry-key
          path: artifact_key.txt