name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Decode GCP Credentials
      run: echo "$GCP_CREDENTIALS" | base64 -d > gcp-credentials.json
      env:
        GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}

    - name: Initialize Terraform
      run: terraform init

    - name: Apply Terraform
      run: terraform apply -auto-approve -var "project=${{ secrets.GCP_PROJECT_ID }}" -var "region=europe-west2"
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/gcp-credentials.json

    - name: Build Docker Image
      run: docker build --platform linux/amd64 --no-cache -t europe-west2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/ttt-gamedev-auth-artifact-registry/ttt-gamedev-auth-micro:latest .

    - name: Authenticate with Google Artifact Registry
      run: echo ${{ secrets.GCP_CREDENTIALS }} | docker login -u _json_key --password-stdin https://europe-west2-docker.pkg.dev

    - name: Push Docker Image
      run: docker push europe-west2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/ttt-gamedev-auth-artifact-registry/ttt-gamedev-auth-micro:latest
