name: Provisioning Resources CI

on:
  push:
    branches:
      - main

jobs:
  provision_resources:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Decode GCP Credentials
        run: |
          echo "$GCP_CREDENTIALS" | base64 -d > gcp-credentials.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=${GITHUB_WORKSPACE}/gcp-credentials.json" >> $GITHUB_ENV
        env:
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}

      - name: Initialize Terraform
        run: terraform init
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/gcp-credentials.json

      - name: Apply Terraform
        run: terraform apply -auto-approve -var "project=${{ secrets.GCP_PROJECT_ID }}" -var "region=${{ secrets.GCP_REGION }}" -var "repository_id=${{ secrets.ARTIFACT_REPO_NAME }}" -var "zone=${{ secrets.GCP_ZONE }}"
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/gcp-credentials.json

      - name: Capture VM External IP to File
        run: |
          terraform output -raw vm_external_ip > vm_external_ip.txt

      # Install jq for JSON processing
      - name: Install jq
        run: sudo apt-get install jq

      - name: Debug Terraform JSON Output
        run: terraform output -json

      - name: Capture Artifact Registry Service Account Key to File
        run: |
          terraform output -json | jq -r '.artifact_registry_service_account_key.value.key' > artifact_key.txt

      # Optional: Debugging step to print the entire Terraform JSON output
      # - name: Debug Terraform JSON Output
      #   run: |
      #     terraform output -json

      # Store the IP and key in the GitHub workspace
      - name: Store Files in Workspace
        run: |
          mkdir -p ${{ github.workspace }}/secrets
          mv vm_external_ip.txt ${{ github.workspace }}/secrets/
          mv artifact_key.txt ${{ github.workspace }}/secrets/
